### PR TITLE
program to check whether array is sorted and rotated

### PR DESCRIPTION
**Pull request by Ashishadhikari123**
This is a program to check whether array is sorted(non decreasing order) and rotated.

### CODE REVIEW

**Comment by Ashishadhikari123** [comment]
Why your GitHub repo excluded from hacktoberfest

**Comment by Sushreesatarupa** [comment]
All the data structures and algorithms repos are excluded from
hacktoberfest due to poor quality contribution issues!

**Comment by Ashishadhikari123** [comment]
It means all other people's repo of dsa also excluded :(

**Comment by Sushreesatarupa** [comment]
Ya !

Except dsa repos of educational sites

**Pull request merged**
