### PR TITLE
ADDED New program inArray section

### PR DESCRIPTION
**Pull request by kraticodes**
<hr>

## Description 📜

added a program to fine the maximum and the minimum element in an array.

<hr>

## Type of change 📝

- [x] Code
- [ ] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Notes (Handwritten notes, cheatsheets, presentations, mind-maps)
- [ ] Others (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Introduction
- [ ] Mathematics
- [ ] Bit Magic
- [ ] Recursion
- [x] Arrays
- [ ] Searching 
- [ ] Sorting
- [ ] Matrix
- [ ] Hashing
- [ ] String
- [ ] Linked List
- [ ] Stacks
- [ ] Queue
- [ ] Deque
- [ ] Tree
- [ ] Binary Search Tree
- [ ] Heap
- [ ] Graph
- [ ] Greedy
- [ ] Backtracking
- [ ] Dynamic Programming
- [ ] Trie
- [ ] Segment Tree
- [ ] Disjoint Set
- [ ] Others

<hr>

## Checklist ✅

- [x] I follow Contributing Guidelines & Code of conduct of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by kraticodes** [comment]
plz review!

**Comment by kraticodes** [comment]
What does this mean? Is this project not included in hacktoberfest2021?

**Comment by kraticodes** [comment]
Plz help!

**Comment by Sushreesatarupa** [comment]
All the data structures and algorithms repos are excluded from
hacktoberfest due to poor quality contribution issues!

**Comment by kraticodes** [comment]
okay,  But you still can merge this PR, right?

**Comment by Sushreesatarupa** [comment]
Ya ofcourse

I'm busy for 2 days on a business proposal, after that I'll take a look at
all the prs and merge the valid ones!

**Comment by Sushreesatarupa** [comment]
> okay, But you still can merge this PR, right?

Ya ofcourse

 I'll take a look at all the prs and merge the valid ones!

**Pull request closed without merging**
